baseURL = "/"
languageCode = "en-us"
title = "Mitch Henderson"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
# hasCJKLanguage = true  # If Chinese/Japanese/Korean is your main content language, enable this to make wordCount works right.
rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
googleAnalytics = "UA-154979770-1"

[author]
  name = "Mitch Henderson"
  
[taxonomies]
  tag = "tags"
  
[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  # themeColor = "#494f5c"

  homeSubtitle = "Sports Science | Athletic Performance"
  # footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  # bgImg = ""  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = "https://github.com/username/repository/commit/"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  relatedPosts = false  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields
  
  # Add custom css
  # customCSS = ["css/foo.css", "css/bar.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "email"
    url = "mailto:mail@mitchhenderson.org"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/mitchhendo_"
    
  [[params.social]]
    name = "github"
    url = "https://github.com/mitchhenderson"

  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/mitch-henderson-9761b8114/"
    
   [[params.social]]
    name = "youtube"
    url = "https://www.youtube.com/channel/UCMt6OBIhnfyaul5M2JgudQg?view_as=subscriber"

[menu]

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 10

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 20